CREATE DATABASE GILMORE;

CREATE USER 'gilmore'@'localhost' IDENTIFIED BY REPLACE-ME;

GRANT ALL PRIVILEGES ON GILMORE.* TO 'gilmore'@'localhost';

USE GILMORE;

CREATE TABLE IF NOT EXISTS GILMORE_GAME
(
  NAME VARCHAR(64) NOT NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE IF NOT EXISTS GILMORE_GAME_SUBSCRIBER
(
  GAME VARCHAR(64) NOT NULL,
  USER VARCHAR(64) NOT NULL,
  PRIMARY KEY (GAME, USER),
  FOREIGN KEY (GAME) REFERENCES GILMORE_GAME (NAME)
);

CREATE TABLE IF NOT EXISTS GILMORE_CUSTOM_COMMANDS
(
  COMMAND     VARCHAR(256)  NOT NULL,
  DESCRIPTION LONGTEXT NOT NULL,
  PRIMARY KEY (COMMAND)
);

CREATE TABLE IF NOT EXISTS GILMORE_MUTE
(
  ID VARCHAR(64) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS GILMORE_COMMAND_PERMISSION
(
  COMMAND VARCHAR(256) NOT NULL,
  ROLEID  VARCHAR(64) NOT NULL,
  PRIMARY KEY (COMMAND, ROLEID)
);