echo ""
echo "================================="
echo "   Take my love, take my land."
echo "  Take me where I cannot stand."
echo ""
echo "  I don't care, I'm still free."
echo " You can't take the sky from me."
echo "================================"
echo ""