package nl.codefox.gilmore.util;

import net.dv8tion.jda.core.EmbedBuilder;
import net.dv8tion.jda.core.entities.MessageEmbed;
import nl.codefox.gilmore.config.GilmoreConfiguration;

import java.awt.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;

public class GilEmbedBuilder extends EmbedBuilder {

	private long startTime;

	public GilEmbedBuilder() {
		this.startTime = System.currentTimeMillis();
		this.setColor(new Color(0, 255, 0));
	}

	@Override
	public MessageEmbed build() {
		Date date = new Date();
		DateFormat df = new SimpleDateFormat("EEE MMM dd'rd', yyyy 'at' HH:mm zzz");
		df.setTimeZone(TimeZone.getTimeZone("UTC"));

		String footerBuilder = String.format("This was generated by Gilmore %s", GilmoreConfiguration.getInstance().getVersion()) +
				" | " +
				df.format(date) +
				" | " +
				"*" + String.valueOf(System.currentTimeMillis() - startTime) + " ms*";

		this.setFooter(footerBuilder, null);
		return super.build();
	}

}
